services:
  - type: web
    name: business-portal
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn business_portal.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: business_portal.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: business-portal.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: business-portal-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin
    plan: free
    disk:
      name: business-portal-disk
      mountPath: /opt/render/project/src/media
      sizeGB: 1

databases:
  - name: business-portal-db
    databaseName: business_portal
    user: business_portal_user
    plan: free 