# Generated by Django 5.2.4 on 2025-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='google_pay_qr',
            field=models.FileField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paytm_qr',
            field=models.FileField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
