# Generated by Django 5.2.4 on 2025-07-11 15:48

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Cafe', 'Café'), ('Dhaba', 'Dhaba'), ('Cab Service', 'Cab Service'), ('Home Stay', 'Home Stay'), ('Dharamshala', 'Dharamshala'), ('Adventure', 'Adventure'), ('ParkWater', 'ParkWater'), ('ParkTravel', 'ParkTravel'), ('Agency Tour Packages', 'Agency Tour Packages'), ('Guide Services', 'Guide Services'), ('Car/Bike Rental', 'Car/Bike Rental'), ('Temple/Pilgrimage Services', 'Temple/Pilgrimage Services'), ('Other', 'Other')], max_length=177),
        ),
    ]
