# Generated by Django 5.2.4 on 2025-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0002_business_business_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AddField(
            model_name='business',
            name='google_business_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='year_of_establishment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
