# Generated by Django 5.2.4 on 2025-07-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0002_business_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='payment_screenshot',
        ),
    ]
