# Generated by Django 5.2.4 on 2025-07-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0003_remove_business_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner_alternate_area_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_alternate_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_phone_area_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_whatsapp_area_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
