# Generated by Django 5.2.4 on 2025-07-25 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0003_remove_business_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='business_listings.business'),
        ),
    ]
