# Generated by Django 5.2.4 on 2025-07-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0004_business_owner_alternate_area_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='owner_alternate_area_code',
            new_name='owner_area_code',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_phone_area_code',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_whatsapp_area_code',
        ),
    ]
