# Generated by Django 5.2.4 on 2025-07-12 05:28

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0005_rename_owner_alternate_area_code_business_owner_area_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ac_nonac',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='available_drivers',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='pricing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='service_area_coverage',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Within City', 'Within City'), ('Outstation', 'Outstation'), ('Both', 'Both'), ('Other', 'Other')], max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='vehicle_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Auto', 'Auto'), ('Bike', 'Bike'), ('Other', 'Other')], max_length=25, null=True),
        ),
    ]
