# Generated by Django 5.2.4 on 2025-07-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0006_business_ac_nonac_business_available_drivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ac_nonac_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='available_drivers_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='service_area_coverage_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='vehicle_types_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
