# Generated by Django 5.2.4 on 2025-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0007_business_ac_nonac_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='changing_rooms_lockers',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='entry_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='safety_certification',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='safety_certification_file',
            field=models.FileField(blank=True, null=True, upload_to='safety_certifications/'),
        ),
        migrations.AddField(
            model_name='business',
            name='total_rides_activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
