# Generated by Django 5.2.4 on 2025-07-12 05:41

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0008_business_changing_rooms_lockers_business_entry_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='customization_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='destinations_covered',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='package_types_offered',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Solo', 'Solo'), ('Family', 'Family'), ('Honeymoon', 'Honeymoon'), ('Group', 'Group'), ('Other', 'Other')], max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='package_types_offered_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='special_offers_discounts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='transport_accommodation_included',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='transport_accommodation_included_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
