# Generated by Django 5.2.4 on 2025-07-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0009_business_customization_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='brochure_flyer',
            field=models.FileField(blank=True, null=True, upload_to='verification_uploads/'),
        ),
        migrations.AddField(
            model_name='business',
            name='gst_certification',
            field=models.FileField(blank=True, null=True, upload_to='verification_uploads/'),
        ),
        migrations.AddField(
            model_name='business',
            name='license_certification',
            field=models.FileField(blank=True, null=True, upload_to='verification_uploads/'),
        ),
        migrations.AddField(
            model_name='business',
            name='menu_tariff_card',
            field=models.FileField(blank=True, null=True, upload_to='verification_uploads/'),
        ),
    ]
