# Generated by Django 5.2.4 on 2025-07-12 05:57

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0010_business_brochure_flyer_business_gst_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ongoing_discounts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_modes_accepted',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UPI', 'UPI'), ('Debit/Credit Card', 'Debit/Credit Card'), ('Net Banking', 'Net Banking'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_modes_accepted_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
