# Generated by Django 5.2.4 on 2025-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0011_business_ongoing_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='declaration_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
