# Generated by Django 5.2.4 on 2025-07-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0012_business_declaration_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='admin_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='business_listings.category'),
        ),
    ]
