# Generated by Django 5.2.4 on 2025-07-12 07:42

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0013_business_admin_review_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category_specific_additions',
            field=models.CharField(blank=True, choices=[('hotels', 'Hotels / Home Stays / Resorts'), ('restaurants', 'Restaurants / Cafes / Dhabas'), ('cab', 'Cab / Taxi / Rental Services'), ('water_parks', 'Water Parks / Adventure Parks / VR-Zone etc'), ('travel', 'Travel & Tour Packages')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='cuisine_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Fast Food', 'Fast Food'), ('Other', 'Other')], max_length=41, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wi-Fi', 'Wi-Fi'), ('AC', 'AC'), ('Parking', 'Parking'), ('Breakfast', 'Breakfast'), ('Other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='live_music_pet_friendly',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Live Music', 'Live Music'), ('Pet Friendly', 'Pet Friendly'), ('Family Seating', 'Family Seating')], max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='other_business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='room_types_offered',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite'), ('Dormitory', 'Dormitory'), ('Other', 'Other')], max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='seating_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='total_number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='veg_nonveg',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Both', 'Both'), ('Other', 'Other')], max_length=22, null=True),
        ),
    ]
