# Generated by Django 5.2.4 on 2025-07-12 07:48

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0014_business_category_specific_additions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='available_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Online Booking', 'Online Booking'), ('Walk-in Customers', 'Walk-in Customers'), ('Home Delivery', 'Home Delivery'), ('Pickup/Drop Service', 'Pickup/Drop Service'), ('24x7 Helpline', '24x7 Helpline'), ('Reservation Required', 'Reservation Required'), ('Other', 'Other')], max_length=107, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='available_services_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
