# Generated by Django 5.2.4 on 2025-07-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0015_business_available_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='operating_days',
            field=models.CharField(blank=True, choices=[('Monday-Friday', 'Monday-Friday'), ('Monday-Saturday', 'Monday-Saturday'), ('Monday-Sunday', 'Monday-Sunday'), ('Tuesday-Saturday', 'Tuesday-Saturday'), ('Wednesday-Sunday', 'Wednesday-Sunday'), ('Thursday-Monday', 'Thursday-Monday'), ('Friday-Tuesday', 'Friday-Tuesday'), ('Saturday-Wednesday', 'Saturday-Wednesday'), ('Sunday-Thursday', 'Sunday-Thursday'), ('All Days', 'All Days (7 days a week)'), ('Weekends Only', 'Weekends Only'), ('Weekdays Only', 'Weekdays Only'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
