# Generated by Django 5.2.4 on 2025-07-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0016_business_operating_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
