# Generated by Django 5.2.4 on 2025-07-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0017_business_category_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='category_other',
            new_name='cuisine_type_other',
        ),
        migrations.AddField(
            model_name='business',
            name='facilities_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='live_music_pet_friendly_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='veg_nonveg_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
