# Generated by Django 5.2.4 on 2025-07-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0018_rename_category_other_business_cuisine_type_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
